url: hahabafeite.github.io
baseurl: /hahabafeite.github.io

# Site settings
title: BluChs
email: yunli8486@gmail.com
description: "蓝调芝士信息科技，专注VR／AR／MR内容定制开发，多位十年经验资深工程师，靠谱技术团队"


# Team names, titles and social links
people:
- name: Glory
  pic: 1
  position: Lead Developer
  #social:
    #- title: twitter
     # #url: #
    #- title: facebook
      #url: #
    #- title: stack-overflow
      #url: #

- name: 李云
  pic: 2
  position: Team Leader
  #social:
    #- title: Wechat
      #url: #
    #- title: facebook
      #url: #
    #- title: Phone
      #url: #

- name: 谭小超
  pic: 3
  position: Lead Marketer
  #social:
    ##- title: twitter
      #url: #
    #- title: facebook
      #url: #
    #- title: google-plus
      #url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
  #- title: twitter
    #url: http://twitter.com/jekyllrb
  #- title: facebook
    #url:
 # - title: stack-overflow
    #url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket 
   # url: http://bitbucket.org/jekyll
 # - title: github
    #url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
